### PR TITLE
Add parameter for exporting all runs to Platform.export_timeseries_data

### PR DESCRIPTION
**Pull request by fonfon**
Add parameter for exporting all model+scenario runs to `Platform.export_timeseries_data`.

- Bugfix (via updated ixmp.jar): `Platform.export_timeseries_data` should not export data of other models. This happened because ixmp_source `DbDAO.exportTimeseriesData`exported the timeseries of all runs if the run_ids list provided via ixmp was empty, see https://github.com/iiasa/ixmp_source/pull/331/commits/fa18af29b5532b2fb7c1bc68f90e5d5623c1c58a - so if no timeseries existed for the provided model/scenario in `Platform.export_timeseries_data`, all runs were exported instead of none.
- Add a parameter to  `Platform.export_timeseries_data` to allow exporting all model/scenario run combinations

## How to review

Check that tests pass and the used naming is compliant with ixmp: `runs` are not used often in ixmp, maybe there's a more suitable name for the `export_all_runs` parameter 

## PR checklist

- [x] Add or expand tests.
- [x] Add, expand, or update documentation.
- [x] Update release notes.

### CODE REVIEW

**Comment by zikolach** [comment]
`Platform.exportTimeseriesData` method contract is to return all runs if empty (or null) run ID list is provided as parameter (same applies to other parameters) and the Python code doesn't fulfill this contract passing empty list where is should not.

**Comment by fonfon** [comment]
@khaeru 
I changed the default method behavior of `Platform.exportTimeseriesData` in ixmp_source, to not return all runs in case of an empty runid list, and added a parameter to still obtain the old behavior. With these changes the currently failing test succeeds.
If you want you can have a quick look at https://github.com/iiasa/ixmp_source/pull/331 - otherwise I'll just merge it and add the updated ixmp.jar to this PR.

**Comment by khaeru** [comment]
> If you want you can have a quick look at [iiasa/ixmp_source#331](https://github.com/iiasa/ixmp_source/pull/331) - otherwise I'll just merge it and add the updated ixmp.jar to this PR.

I can't review that PR in detail, so please go ahead. This will also need a rebase, since I had to make some CI fixes on `master` since your last changes.

**Comment by khaeru** [comment]
I can review and merge this only once:
- the title and description of the PR are up to date (they seem not to be),
- the PR checklist is complete, and
- the PR is no longer in draft state.

**Comment by fonfon** [comment]
I had left the PR in the draft state on intention because I planned to further update it - it's now ready to be reviewed, sorry that it took a while!

**Review by khaeru — APPROVED** [review]
There is a typo in the addition to the release notes, but will clean this up in a subsequent PR.

**Pull request merged**
