### PR TITLE
Test rixmp using 'testthat'

### PR DESCRIPTION
**Pull request by khaeru**
This PR renames retixmp to rixmp, and adds tests using the standard `testthat` R package. As well:

- R tests are run on all platforms, and on both Travis and Appveyor CI infrastructure.
- Tutorial tests (including Python tutorials) are re-enabled on Appveyor.
- Appveyor configuration is cleaned up.

Key pieces:

- `rixmp/source/tests/`
  - `testthat/test_core.R`: example file with minimal tests of core (Python) `ixmp` features via (R) `reticulate`.
  - `testthat.R`: standard file to invoke `testthat`.
- `tests/test_r.py`: add 1 new fixture and 3 new methods that, in turn, invoke the R tests:
  - `test_r_build_and_check()`: The standard pair of `R CMD build`, `R CMD check` (as run by e.g. CRAN or Travis [as described here](https://docs.travis-ci.com/user/languages/r/)). This is slow because numerous checks are performed in addition to the unit tests.
  - `test_r_testthat()`: run *only* the unit tests.

To test-drive *just* these new tests, run one of:
```
$ pytest -k 'r_build'
$ pytest -k 'r_testthat'
```

## To complete
- [x] **@adrivinca, @peterkolp**: please provide code (e.g. an example R script) that breaks retixmp. If you can convert this into a test (i.e. by editing `test_core.R`), please do. (I can show you how to PR that into my `khaeru:r-testing` branch; or, simply send me the code for the tests.) Or, I can create the test.
  - We will complete this PR without this test, then (if needed) copy the code/infrastructure to develop tests for reticulate-message_ix, or open a new issue if the message_ix work reveals things to be tested in retixmp.

**Anyone:** please help answer the following questions:
- [x] Q1: the `DESCRIPTION` files for rixmp and retixmp show versions of 0.0.0.9000 and 0.0.1, respectively. Should these not be the same as the ixmp Python package?
  - *A1:* updated to 0.1.3.9000. This will need to be set to 0.2.0 when the next release is made.
- [x] Q2: the existing method `test_run()` in `test_r.py` invokes the file `tests/r_tests.r`. I plan to convert this to a `testthat` test. What does the line `source(file.path(Sys.getenv("IXMP_R_PATH"), "ixmp.R"))` do? This file does not seem to exist in the repository.
  - *A2:* removed.
- [x] Q3: `install.bat` invokes `retixmp/build_retixmp.R` and `rixmp/build_rixmp.R`. None of these seem to be documented. How is the user supposed to use these, in conjunction with the [main installation instructions for message_ix/ixmp](https://message.iiasa.ac.at/en/latest/getting_started.html)?
  - *A3:* removed, in favour of calling `R CMD INSTALL` directly.
- [x] Q4: should we remove the older `rixmp` entirely?
  - *A4:* kept as `rixmp.legacy`, with a prominent deprecation notice.

**@khaeru:** standard PR checklist:
  - [x] Tests added.
  - [x] Documentation added — preview at https://ixmp-khaeru.readthedocs.io/en/r-testing/api.html.
  - [x] Description in RELEASE_NOTES.md added.

### CODE REVIEW

**Comment by gidden** [comment]
> Q2: the existing method test_run() in test_r.py invokes the file tests/r_tests.r. I plan to convert this to a testthat test. What does the line source(file.path(Sys.getenv("IXMP_R_PATH"), "ixmp.R")) do? This file does not seem to exist in the repository.

That is likely left over from the very old days (2+ years ago), where we did not have an installable r package. @adrivinca since made it installable, but I don't think anyone has every looked at this test since then. It can likely be thrown away entirely.

**Comment by adrivinca** [comment]
Thanks @kaheru for this PR.
I think there are some aspects worth being discussed together.
Starting with the test where retixmp breaks,  we faced problems when working with message_ix (at least for Peter) that are not happening just using ixmp. 

Should we make similar tests in the message_ix repository?

Q1. Any name/numbering is fine for me, let's agree on one.

Q2. The IXMP_R_PATH was used by rixmp. If we want to get rid completely of the old rixmp package I can clean it up. This means backward incompatibility of the new ixmp version (for some R users).

Q3. Concerning the build files, i think they should not be used by the users, are supposed to be used only during the automatic installation phase. Maybe we can make sure that this happen with any installation method (bat file or not)

R package documentation is another topic and it should be embedded in the R package as in the ixmp documentation

I will soon work on the tests and add some

**Comment by khaeru** [comment]
As of “Fiddle with Appveyor config 33”, the R dependencies are installed and tests run on Appveyor :raised_hands:

**Comment by khaeru** [comment]
Okay, we now have R tests, working on all CI infrastructure. Two remaining issues to be resolved:

> * [ ]  Q4: should we remove the older `rixmp` entirely?

This needs a higher-level approval. @volker-krey @gidden @danielhuppmann any thoughts? Who would be affected? From the number of commits above, you can see that it was (very…) laborious simply to ensure that `retixmp` is *testable*—even though there are only a few, very simple tests. I imagine it would be less costly to help any `rixmp` users migrate, than to repeat this effort for `rixmp`, *plus* making any improvements to the `rixmp` code.

The alternative is to leave it for now with a big warning/caveat box in the documentation (see the preview linked in the PR description), and remove it at some point later.

> * [ ]  Q3: `install.bat` invokes `retixmp/build_retixmp.R` and `rixmp/build_rixmp.R`. None of these seem to be documented. How is the user supposed to use these, in conjunction with the [main installation instructions for message_ix/ixmp](https://message.iiasa.ac.at/en/latest/getting_started.html)?

@adrivinca and I will resolve this on 2019-05-13. I suspect the best approach is to remove the files entirely, and then simply call `R CMD build` / `R CMD INSTALL` directly from `install.bat`.

**Comment by khaeru** [comment]
> The alternative is to leave it for now with a big warning/caveat box in the documentation (see the preview linked in the PR description), and remove it at some point later.

We decided to go with this.

Kudos to @adrivinca for figuring out the trick to get reticulate to use the proper path, as implemented in 1035a15.

@gidden I've asked for your review since this PR makes a number of changes to the test config.

**Comment by gidden** [comment]
Hi folks, we briefly discussed this in our developer meeting today. @adrivinca would you mind providing a short update here as to final steps required to get this PR merged? Thanks!

**Comment by adrivinca** [comment]
- I need to add relevant test *which I have done, just need to push

- rename the packages as we agreed during the meeting> retixmp> rixmp ; rixmp > rixmp-legacy
I will do it soon

**Comment by adrivinca** [comment]
I did a PR to @khaeru 's branch with final tests and renamed packages.
It should be all fine. But it would be good if anyone gives it a try/look, especially concerning the renaming, I hope the documentation is clear enough to avoid confusion with old packages.

**Comment by gidden** [comment]
@iiasa/messageix-r-devs could one of you please review @adrivinca's PR? thanks!

**Comment by vruijven** [comment]
> 
> 
> @iiasa/messageix-r-devs could one of you please review @adrivinca's PR? thanks!

I can give it a try, but finishing the GEIDCO runs and report has my priority the next few days.

**Comment by adrivinca** [comment]
So, to get this dove, @khaeru  could you please accept the [PR](https://github.com/khaeru/ixmp/pull/3) I made to your branch? otherwise my last change will not be in here.

Only after it will make sense to review, which might consist in two simple tasks.

- installing ixmp and seeing if all the tests pass, eventually also go through the tutorials
- check whether the ixmp documentation at the API page is clear, especially concerning the new naming of the R packages

**Comment by khaeru** [comment]
> So, to get this done, @khaeru could you please accept the [PR](https://github.com/khaeru/ixmp/pull/3) I made to your branch? otherwise my last change will not be in here.

Thanks, done via cherry-picking 2 commits.

**Comment by khaeru** [comment]
Huge thanks to @adrivinca for the R knowledge and team effort.

**Pull request merged**
