### PR TITLE
Filter all data from one Scenario by a set element; add utils.diff()

### PR DESCRIPTION
**Pull request by khaeru**
This PR adds features to get data from every parameter in an `ixmp.Scenario` that matches some filters, e.g. a single value on a single dimension. In message_ix this makes it possible to get all parameter data related to a single `technology`, i.e. iiasa/message_ix#267; but the functionality is generalized here so users can find other applications for it.

## How to review

- Read the new tests, including `test_diff` and ensure they cover easily imaginable use cases.
- Note that CI checks, including new tests, pass.
- Run the new CLI command against some existing, “real world” scenarios, e.g. things like:
  ```
  $ message-ix --url="ixmp://my-platform/my-model/my-scenario" export example.xlsx -- technology=coal_ppl,wind_ppl
  ```

## PR checklist

- [x] Add basic functionality to return data across all parameters.
- [x] Modify `to_excel()` to accept filters.
- [x] Add 2-scenario "diff" utility per https://github.com/iiasa/message_ix/pull/267#issuecomment-623395698.
- [x] Add tests for all of the above.
- [x] Add documentation.
- [x] Update release notes.
- [x] Boost code coverage: test when one param is missing from each scenario passed to `diff()`.

### CODE REVIEW

**Comment by khaeru** [comment]
Hi @ClaraLuisa @behnam-zakeri, I'm requesting your review of this code.

I think I've managed to preserve a superset of the features that you (respectively) provided and requested in iiasa/message_ix#267; however, the code is now usable for any dimension(s) of any ixmp Scenario. Please see the "How to review" in the description above.

Based on your feedback or questions, I will then update the documentation so the functionality and how to use it is made clear.

**Comment by khaeru** [comment]
> Based on your feedback or questions

Seeing none, I'll merge this. If the feature could be enhanced somehow, please open an issue to describe how.

**Comment by behnam-zakeri** [comment]
Thanks a lot @khaeru for this piece of work, which is very useful. Sorry for the late feedback. As mentioned in the meeting, it will be useful to add a line or two to show how the functionality can be used in a script without exporting the data to Excel.

**Comment by khaeru** [comment]
> it will be useful to add a line or two to show how the functionality can be used in a script without exporting the data to Excel.

Since this PR is already merged, can you open a new issue for this improvement?

**Pull request merged**
