### PR TITLE
Add Uniform Resource Locators (URLs) for Scenarios

### PR DESCRIPTION
**Pull request by khaeru**
Implements #166 by providing utils.parse_url() and Scenario.from_url(). This expands on code that's been piloted via iiasa/message_data#41 and has proved useful.

**PR checklist:**

- [x] Tests added.
- [x] Documentation added.
- [x] Release notes updated.

### CODE REVIEW

**Comment by khaeru** [comment]
@OFR-IIASA @behnam-zakeri here is the documentation for the 2 new methods, for help in review:
https://github.com/iiasa/ixmp/blob/f22e0f304947dcfd182ed8fc076da9a10069f86a/ixmp/utils.py#L53-L89
https://github.com/iiasa/ixmp/blob/f22e0f304947dcfd182ed8fc076da9a10069f86a/ixmp/core.py#L860-L884

**Comment by behnam-zakeri** [comment]
Thanks @khaeru for this addition. I tested this on machine and the tests work and different combination of scenario identifiers work too (default or not, version number given or not, etc.). Just two points:
1. As discussed in persion, for getting connected to a central database through a `*.properties' file, that file needs to be under the default folder of ixmp database, i.e., `C:\Users\...\.local\share\ixmp`.
2. A minor question: the features loads the _Platform_ and a scenario instance together. As such, some of the methods of the _Platform_ cannot be used/assessed before making sure that the URL is correct for model/scenario combination too. 
For example, if I call a URL as `scen, mp = Scenario.from_url('ixmp://local/testtt/baseline')`, where the model name `test` is spelled wrongly, the call returns an error as this model is not in the database. However, the call doesn't return the Platfrom (`mp`) neither. So I'm not able to check the correct name of this scenario in the database by the _Platform_ method of `mp.scenario_list()`. Maybe I miss something out, or this is not an intended outcome.

**Comment by khaeru** [comment]
> 2. For example, if I call a URL as `scen, mp = Scenario.from_url('ixmp://local/testtt/baseline')`, where the model name _test_ is spelled wrongly, the call returns an error as this model is not in the database. However, the call doesn't return the Platfrom (`mp`) neither. So I'm not able to check the correct name of this scenario in the database by the _Platform_ method of `mp.scenario_list()`. Maybe I miss something out, or this is not an intended outcome.

This is a useful point. IOW:
- In *script* use, not finding the model/scenario names is a failure, and the function should raise an exception.
- In *interactive* use (e.g. in a notebook), the user will want to play with the `mp` object. So `None` should be returned for `scen`, and only a warning (rather that exception) should be given.

Now I just need to decide which should be the default…

**Comment by khaeru** [comment]
I will refresh this after #198 goes in.

Currently, it's a big ambiguous how the `PLATFORM` part of the URL relates especially to HSQLDBs that may be scattered around the user's machine. Either the database would have to be in a specific directory (limiting), or it might contain path separators (`/`), which would make the URL hard to read/interpret (defeats the purpose).

After #198, this becomes much simpler: `PLATFORM` will refer to the name of a platform config in the user's config.json file, i.e. previously set with `ixmp platform add [...]`.

**Comment by khaeru** [comment]
@behnam-zakeri I have now updated this to use the new config system, so the PLATFORM part of a URL is always a configured platform name. As well, per your request I added an argument to from_url(). When loading the Scenario fails:
- errors='warn' (default) displays a warning but still returns (None, mp).
- errors='raise' raises the Exception to be caught by other Python code.

Please re-review when you have a moment!

**Comment by behnam-zakeri** [comment]
@khaeru, thanks for improving this and adding the warning flag. I tested this and works as expected.

**Pull request merged**
