### PR TITLE
Switch to RTD sphinx theme

### PR DESCRIPTION
**Pull request by khaeru**
Live preview: https://ixmp.readthedocs.io/en/feature-rtd/

**PR checklist:**

- [x] Tests added
- [x] Documentation added
- [x] Description in RELEASE_NOTES.md added

### CODE REVIEW

**Comment by gidden** [comment]
@khaeru is this good to be reviewed/merged?

**Comment by khaeru** [comment]
No, I'll need to update the theme to match the one we chose for MESSAGEix.

Will do that today, and then request a review.

**Comment by gidden** [comment]
@khaeru what's the link for the branch's rendered docs?

**Comment by gidden** [comment]
looks great! Thanks @khaeru

**Pull request merged**
