### PR TITLE
update jdbc.py to allow using .remove_set()

### LINKED ISSUE #250: Error when removing scenario sets using scenario.remove_set()
Trying to add some tests for another `Scenario` _class_ method and using the tutorial notebooks, I encountered the following problem when using the method `remove_set()`:

```
horizon = range(2010, 2041, 10)
scenario.add_horizon({"year" : [2000, 2040, 2200, 2500]}, 2200)
scenario.remove_set("year")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-cb7b55997b7e> in <module>
      1 horizon = range(2010, 2041, 10)
      2 scenario.add_horizon({"year" : [2000, 2040, 2200, 2500]}, 2200)
----> 3 scenario.remove_set("year")
c:\users\lovat\documents\github\francescolovat\ixmp\ixmp\core.py in remove_set(self, name, key)
    889         """
    890         if key is None:
--> 891             self._backend('delete_item', 'set', name)
    892         else:
    893             self._backend('item_delete_elements', 'set', name,
c:\users\lovat\documents\github\francescolovat\ixmp\ixmp\core.py in _backend(self, method, *args, **kwargs)
    356     def _backend(self, method, *args, **kwargs):
    357         """Convenience for calling *method* on the backend."""
--> 358         return self.platform._backend(self, method, *args, **kwargs)
    359 
    360     # functions for platform management
c:\users\lovat\documents\github\francescolovat\ixmp\ixmp\backend\base.py in __call__(self, obj, method, *args, **kwargs)
     23         for the method name, e.g. 'ts_{method}'.
     24         """
---> 25         return getattr(self, method)(obj, *args, **kwargs)
     26 
     27     def close_db(self):  # pragma: no cover
c:\users\lovat\documents\github\francescolovat\ixmp\ixmp\backend\jdbc.py in delete_item(self, s, type, name)
    501 
    502     def delete_item(self, s, type, name):
--> 503         getattr(self.jindex[s], f'remove{type.title()}')()
    504         self.cache_invalidate(s, type, name)
    505 
TypeError: No matching overloads found for at.ac.iiasa.ixmp.objects.MsgScenario.removeSet(), options are:
	public void at.ac.iiasa.ixmp.objects.Scenario.removeSet(java.lang.String) throws at.ac.iiasa.ixmp.exceptions.IxException
	at JPMethod::findOverload(native\common\jp_method.cpp:242)
	at JPMethod::findOverload(native\common\jp_method.cpp:245)
	at JPMethod::invoke(native\common\jp_method.cpp:253)
	at PyJPMethod::__call__(native\python\pyjp_method.cpp:142)
```

After discussing with @zikolach, he found out what could be the reason of it.

It has to deal with the changes in commit https://github.com/iiasa/ixmp/commit/61b977601ab3ed091153c079385a598ad652bc6.

The solution is presented in PR.

### PR DESCRIPTION
**Pull request by francescolovat**
This PR closes #250. 

According to @zikolach, the error that does not allow remove_set() to function is found in the jdbc.py file.

After doing this modification `remove_set()` is working in my PC.

Are any other modifications to be done related to this method?

- [x] A test should be added to test this method.
- [x] Confirmation that `remove_set()` is working by other users.

### CODE REVIEW

**Comment by zikolach** [comment]
@francescolovat as mentioned it happened most probably due to the lack of tests. Could you please add a test case for this method to prevent it in the future?

**Comment by francescolovat** [comment]
@zikolach @khaeru with https://github.com/iiasa/ixmp/pull/251/commits/d18e85e415f12642bffa57e5b11d8673d08e841c I tried to add an extra case to `test_set` for completely removing a set, but I could not avoid this test failing anymore since apparently I can't initialize a set and then remove it easily. I tried to remove an existing set but due to it's dependencies to other parameters and variables I could not do it. Any suggestions?

**Comment by francescolovat** [comment]
I'm not sure, however, if this test urges to be included in the 2.0 milestone. At the moment, I've added it to the 3.0

**Comment by khaeru** [comment]
> Any suggestions?

See e4d6876! Let's see if the CI checks pass.

**Comment by francescolovat** [comment]
Thanks again @khaeru ! 

I'm pretty sure I tried a very similar test to the one you've added but still didn't work to me... I'm happy you made it work!

**Pull request merged**
